# Sir, if you're reading this, I seriously am not able to test this, my VM is barely breathing. My laptop can't survive one; let alone five VMs. 8 gigs of RAM and 14.1 gigs left (installed one Ubuntu VM. ONE. AND IT'S NOW 14.1G LEFT IT WAS 34G BEFORE GOD) of my storage on a 2090. HELP

# if you want to do this just change the inventory file to fit the VM's IP addresses.

---
- hosts: all
  become: true
  pre_tasks:

  - name: install updates (centos)
    tags: always
    dnf:
      update_only: yes
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: install updates (ubuntu)
    tags: always
    apt:
      upgrade: dist
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

# SQL
- hosts: enterprise
  become: true
  tasks:

  - name: install Postgresql (ubuntu)
    tags: postgresql
    apt:
      name:
        - postgresql
        - python3-psycopg2
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install Postgresql (CentOS)
    tags: postgresql
    dnf:
      name:
        - postgresql-server
        - python3-psycopg2
      state: latest
    when: ansible_distribution == "CentOS"

  - name: initialize postgresql database (centos)
    tags: postgresql
    shell: postgresql-setup initdb
    when: ansible_distribution == "CentOS"

  - name: start and enable postgresql
    tags: postgresql
    systemd:
      name: postgresql
      state: started
      enabled: yes

  - name: change motd
    tags: always
    copy:
      content: "Ansible Managed by alexis-acad (Deniega)\n"
      dest: /etc/motd

# Nagios
- hosts: monitoring
  become: true
  tasks:

  - name: install nagios prerequisites (ubuntu)
    tags: nagios
    apt:
      name:
        - apache2
        - php
        - gcc
        - make
        - wget
      state: latest
    when: ansible_distribution == "Ubuntu"

  - name: install nagios prerequisites (centos)
    tags: nagios
    dnf:
      name:
        - httpd
        - php
        - gcc
        - make
        - wget
      state: latest
    when: ansible_distribution == "CentOS"

  - name: start and enable apache (ubuntu)
    tags: nagios
    systemd:
      name: apache2
      state: started
      enabled: yes
    when: ansible_distribution == "Ubuntu"

  - name: start and enable apache (centos)
    tags: nagios
    systemd:
      name: httpd
      state: started
      enabled: yes
    when: ansible_distribution == "CentOS"

  - name: change motd
    tags: always
    copy:
      content: "Ansible Managed by alexis-acad (Deniega)\n"
      dest: /etc/motd

